queue:
  name: Agentpool-15
  
trigger:
  -fix-ci

variables:
  buildConfiguration: 'Release'
  
#Your build pipeline references an undefined variable named ‘Parameters.RestoreBuildProjects’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘Parameters.RestoreBuildProjects’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build pipeline references an undefined variable named ‘Parameters.TestProjects’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore

      projects: '**/*.csproj'


  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '**/*.csproj'

      arguments: '--configuration $(BuildConfiguration)'


  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test

      projects: '**/*Tests/*.csproj'

      arguments: '--configuration $(BuildConfiguration)'

      publishTestResults: false


  - task: VSTest@2
    displayName: 'VsTest - testAssemblies'
    inputs:
      testAssemblyVer2: |
        **\*test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
        **/*[Tt]ests/*.csproj

      codeCoverageEnabled: true

    enabled: false

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TEST-*.xml'

    enabled: false

