queue:
  name: Agentpool-15

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature-*
      - fix-ci

variables:
  buildConfiguration: 'Release'
  projectToBuild: '**/*.csproj'
  testProjectToBuild: '**/*Tests/*.csproj'

#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(projectToBuild)'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(projectToBuild)'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '$(testProjectToBuild)'
      arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true'
      publishTestResults: true
